### ISSUE TITLE
f:new throw a SyntaxError

### ISSUE THREAD

**Issue by watilde** [stdlib/lib#10]
My envs:
- `node -v`: v5.5.0
- stdlib.com version: v0.1.3

Error log:

```
$ stdlib f:new
/usr/local/lib/node_modules/stdlib.com/index.js:4
let host = 'f.stdlib.com';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/stdlib.com/cli/commands/f.js:6:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by trsrm** [comment]
The same issue:
Node v4.2.6
stdlib v0.1.3

**Comment by keithwhor** [comment]
might need to scour some packages to fix this, will look into it, other packages I've developed have been Node 6+ as well. :)
