### ISSUE TITLE
Running `lib logs` without any arguments throws an error

### ISSUE THREAD

**Issue by macdja38** [stdlib/lib#148]
```
lib logs
C:\Users\macdja38\AppData\Roaming\npm\node_modules\lib.cli\cli\commands\logs.js:70
    let wildcard = serviceFilter[serviceFilter.length - 1] === '*';
                                               ^

TypeError: Cannot read property 'length' of undefined
    at LogsCommand.run (C:\Users\macdja38\AppData\Roaming\npm\node_modules\lib.cli\cli\commands\logs.js:70:48)
    at CommandLineInterface.run (C:\Users\macdja38\AppData\Roaming\npm\node_modules\lib.cli\node_modules\cmnd\lib\command_line_interface.js:200:22)
    at Object.<anonymous> (C:\Users\macdja38\AppData\Roaming\npm\node_modules\lib.cli\cli\bin.js:26:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
```

**Comment by keithwhor** [comment]
I've assigned myself to this for now; it's not a breaking bug but it is undesirable, so in my next pass of the CLI updates (there are a few outstanding items here) I'll make sure I tackle it. :)

**Comment by keithwhor** [comment]
Should be fixed as of https://github.com/stdlib/lib/commit/f6bd0c47ddd6406acf66d18a16568043b097ebe7, sorry for the delay! Assumed I'd get to a CLI overhaul long before I actually did. :)

**Comment by macdja38** [comment]
Thanks Keith, have a nice day!
