### ISSUE TITLE
Error running lib . after lib get

### ISSUE THREAD

**Issue by MonsterDeveloper** [stdlib/lib#164]
I started my project on code.xyz, and then I wanted to move to local development, so I installed lib.cli, did `lib init` and then `lib get [xxx]`. But when I go to project directory and run `lib .`, there is an error. Here is a stack trace.
```
MacBook-Pro-Andrew:dir andrew$ lib .
{ Error: Cannot find module '/Users/andrew/stdlib/xxx/xxx/functions/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (/Users/andrew/.npm-packages/lib/node_modules/lib.cli/node_modules/lib/lib/local.js:44:10)
    at Proxy.__call__ (/Users/andrew/.npm-packages/lib/node_modules/lib.cli/node_modules/lib/lib.js:24:20)
    at __nomethod__Command.run (/Users/andrew/.npm-packages/lib/node_modules/lib.cli/cli/commands/__nomethod__.js:343:40)
    at CommandLineInterface.run (/Users/andrew/.npm-packages/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:200:22)
    at Object.<anonymous> (/Users/andrew/.npm-packages/lib/node_modules/lib.cli/cli/bin.js:26:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module '/Users/andrew/stdlib/xxx/xxx/functions/index.js'
```

**Comment by jacoblee93** [comment]
Hey @MonsterDeveloper! Try adding `"build": "faaslang"` to the `stdilib` field of your service's `package.json` file. That should fix it for now, I've just created a PR for a more robust fix.

**Comment by MonsterDeveloper** [comment]
Thanks @jacoblee93! It works now. Also I think you need to specify somewhere in stdlib docs that to call certain function on localhost you need to do `lib .[function-name]`, because I wasn't able to find information about that in the docs.

**Comment by jacoblee93** [comment]
Ah good. I can update the docs with that quickly as well, thanks!
