### ISSUE TITLE
Error on `lib init`

### ISSUE THREAD

**Issue by IzumiSy** [stdlib/lib#32]
I got this error. Looks probably because of node.js version, but how do I do for this?

```
 $ lib init
/Users/izumisy/.nvm/versions/node/v4.5.0/lib/node_modules/lib/cli/error_log.js:8
    let details = err.details[k];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/izumisy/.nvm/versions/node/v4.5.0/lib/node_modules/lib/cli/commands/login.js:6:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

```
 $ node --version
v4.5.0
```

**Comment by keithwhor** [comment]
Hey there,

stdlib currently requires Node 6 or higher to use the CLI tools. It's the latest LTS release, so I'm not sure we'll be adding compatibility for earlier versions. I see you're using `nvm` so the update should be straightforward. :) 

Let me know if you have any questions!
- Keith

**Comment by IzumiSy** [comment]
@keithwhor Sorry for spending time for me! It seems I missed that line on README. Thanks.
