### ISSUE TITLE
I've tried to setup twice but get this error

### ISSUE THREAD

**Issue by asteriusj** [stdlib/lib#51]
$ lib init

/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/lib.cli/cli/commands/__nomethod__.js:96
        lib({token: token, host: host, port: port})[params.name](...args, kwargs, cb);
                                                                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:97:20
    at Array.forEach (native)
    at CommandLineInterface.load (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:80:44)

**Comment by wKovacs64** [comment]
`lib` requires Node 6.x. At the time you got that error, your `nvm` was using Node 4.7.3.

**Comment by asteriusj** [comment]
that worked, thx

**Comment by keithwhor** [comment]
Thanks @wKovacs64!
