### ISSUE TITLE
Errors when running vue template example

### ISSUE THREAD

**Issue by prodrammer** [stdlib/lib#65]
I'm trying to get this vue template example up and running:

https://docs.stdlib.com/main/#/templates/vue

I initially was getting the error 'Error: No parser found for extension ".json"'. I switched the package.json build setting from "faaslang" to "legacy" as recommended in #61 and now I am getting the following error after hitting the site hosted by the 'lib http' command.

`ryanhaney$ lib http

HTTP development server listening for service appology/test on port 8170

[+http] 
[+http] Webpack is watching the files…
[+http] 
[+http] 
[+http] Hash: 24c6bac3b1895f2e4977
[+http] Version: webpack 2.6.1
[+http] Time: 1937ms
[+http]   Asset    Size  Chunks                    Chunk Names
[+http] main.js  353 kB       0  [emitted]  [big]  main
[+http] 
[function: .appology.test] {"args":[],"kwargs":{}}
{ Error: Cannot find module '/Users/ryanhaney/Projects/stdlib/appology/test/functions/appology/test/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports.e (/usr/local/lib/node_modules/lib.cli/node_modules/lib/lib/local.js:44:10)
    at Proxy.__call__ (/usr/local/lib/node_modules/lib.cli/node_modules/lib/lib.js:24:20)
    at response (/usr/local/lib/node_modules/lib.cli/cli/parser.js:46:26)
    at IncomingMessage.libres.on.e (/usr/local/lib/node_modules/lib.cli/cli/parser.js:119:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) code: 'MODULE_NOT_FOUND' }
[function: .favicon.ico] {"args":[],"kwargs":{}}
{ Error: Cannot find module '/Users/ryanhaney/Projects/stdlib/appology/test/functions/favicon/ico/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports.e (/usr/local/lib/node_modules/lib.cli/node_modules/lib/lib/local.js:44:10)
    at Proxy.__call__ (/usr/local/lib/node_modules/lib.cli/node_modules/lib/lib.js:24:20)
    at response (/usr/local/lib/node_modules/lib.cli/cli/parser.js:46:26)
    at IncomingMessage.libres.on.e (/usr/local/lib/node_modules/lib.cli/cli/parser.js:119:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) code: 'MODULE_NOT_FOUND' }`

**Comment by jacoblee93** [comment]
Hey @ryanhaney,

We haven't merged the new version of the Vue template into the repo yet, but it's now live if you run `lib create -t vue`. Give it a try, and let me know if something's off!
