### ISSUE TITLE
lib init throws "unexpected token" errors

### ISSUE THREAD

**Issue by avemuri** [stdlib/lib#85]
$ lib init
`/usr/local/lib/node_modules/lib.cli/cli/commands/__nomethod__.js:162
        lib(cfg)[params.name](kwargs, ...args, cb);
                                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:97:20
    at Array.forEach (native)
    at CommandLineInterface.load (/usr/local/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:80:44)
`

**Comment by keithwhor** [comment]
You should make sure you're running Node 6.x or higher.

**Comment by keithwhor** [comment]
I'm closing this - please LMK if issue happens again!
