### ISSUE TITLE
Lib init throws initialisation error if STDLIB_ACCESS_TOKEN is missing

### ISSUE THREAD

**Issue by philipphager** [stdlib/lib#88]
I just installed the latest version of stdlib and got the following error while running `lib init`:

```
/usr/local/lib/node_modules/lib.cli/cli/credentials.js:47
      throw new Error(`Please initialize stdlib in directory tree or set STDLIB_ACCESS_TOKEN as environment variable`);
      ^

Error: Please initialize stdlib in directory tree or set STDLIB_ACCESS_TOKEN as environment variable
    at readCredentials (/usr/local/lib/node_modules/lib.cli/cli/credentials.js:47:13)
    at Object.read (/usr/local/lib/node_modules/lib.cli/cli/credentials.js:96:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/lib.cli/cli/commands/tasks/create.js:19:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

My configuration:
nodeJs: v6.11.3
npm: 3.10.10
stdlib: 3.3.0

I was able to fix the issue by creating an empty environment variable `STDLIB_ACCESS_TOKEN`,
but I guess this shouldn't be required to run the init command. Also all subsequent calls, such as lib create.. fail then due to bad requests.

**Comment by keithwhor** [comment]
Hey @philipphager! Thanks for the catch. I've put out a hotfix. Can you try upgrading to `lib.cli@3.3.1` and let me know if the problem persists?

**Comment by philipphager** [comment]
Hey @keithwhor! It worked perfectly! Thank you and props for the impressive response time! Keep up the good work!
